### ISSUE TITLE
Don't publish annotation-processor & common module to maven central

### ISSUE THREAD

**Issue by lilgallon** [IZIVIA/ocpi-toolkit#112]

**Comment by andacata** [comment]
@lilgallon  The `annotation-processor` is still included in the `ocpi-2-2-1` pom, so my project is trying to get the dependency and failing to compile.

**Comment by lilgallon** [comment]
Indeed, I just noticed that, I fix it asap

**Comment by lilgallon** [comment]
I fixed it locally by adding a new gradle configuration called "internal". This configuration can be used for libs that should not be included in generated pom.xml

I build a new version -> 0.0.37

**Comment by lilgallon** [comment]
It should be better now, sorry for the inconvenience, I did not test properly

**Comment by andacata** [comment]
No worries. Thank you for your quick response!!!  :rocket:
