### ISSUE TITLE
Skip NULL values in Connector.tariff_ids

### ISSUE THREAD

**Issue by andacata** [IZIVIA/ocpi-toolkit#130]
I found some partners sending a `null` inside the Connector.tariff_ids array, breaking the deserialization process.

```json
"tariff_ids": [null],
```

I think that skipping the null values inside the array will be beneficial for anyone using the library.

**Comment by lilgallon** [comment]
It sounds like it's an issue on the partner side (tariffs_ids is a list of case-insensitive strings, and it should never contain null values)

Anyway, partners are not perfect, and won't ever be perfect. This is not a case where we would want to throw an error, especially if we can do an easy workaround for it.

The goal of open sourcing this lib is to get feedback from anyone communicating in OCPI. Thanks for your contribution ;)
