### ISSUE TITLE
Partner URL is not a unique identifier

### ISSUE THREAD

**Issue by lilgallon** [IZIVIA/ocpi-toolkit#132]
The lib is designed around the fact that a partner url is unique. It is not the case. There are few cases where it is valid to have the same url but different partners.

This change should be almost backward compatible. The url should use a "id" string as identifier instead of "url" string. Most of the changes will just be the renaming of "url" to "id". But there are some parts of the code were we use the "url" string as an actual url. Only those cases will be impacted to properly use the partner `url` instead of the parameter given which will now be "id" and not "url"

**Comment by andacata** [comment]
:scream: 

Hi @lilgallon , can you share an example of that situation?

**Comment by lilgallon** [comment]
Hi, we have a partner that has the same OCPI url but with different identities. They could use a different DNS entry for each identity, but they don't 😅

In the OCPI protocol there is no mention of partner url being an identifier for a partner. So we had to review the design of the lib to make sure that we do not expect the url to be unique (the users will still be able to use url as identifier if they want though)

**Comment by andacata** [comment]
I was thinking about that from the beginning, but I thought I was wrong. Now I see that I'm not :sweat_smile:

**Comment by lilgallon** [comment]
closed by #133

**Comment by atschabu** [comment]
if we already separate partnerId from url, why don't we store the Url as part of the credentials exchange (when receiving POST /credentials). It merely means that I still need to know the partners versions url in advance, which often slows down offline credentials exchange.

**Comment by lilgallon** [comment]
You are right, we should store url during credentials here:

https://github.com/IZIVIA/ocpi-toolkit/blob/8e9f7a873242046bad248bce6c0d9296e02999dc/ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/credentials/services/CredentialsServerService.kt#L45C1-L56C10

```kotlin
        // Save credentials roles of partner
        partnerRepository.saveCredentialsRoles(
            partnerId = partnerId,
            credentialsRoles = credentials.roles,
        )


        // Save token B, which is in our case the client token, because it's the one that we will use to communicate
        // with the sender
        partnerRepository.saveCredentialsClientToken(
            partnerId = partnerId,
            credentialsClientToken = credentials.token,
        )
```

I create the GH issue
