### ISSUE TITLE
Missing evse_id and connector_id in PATCH location client calls

### ISSUE THREAD

**Issue by atschabu** [IZIVIA/ocpi-toolkit#24]
Both patchEvse and patchConnector are missing the ID for evse and connector in the path

https://github.com/IZIVIA/ocpi-toolkit/blob/486a2f3454ab6c185a10de8cfe221f29dbf9cc23/ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/locations/LocationsCpoClient.kt#L188C1-L188C1

should be
```
      path = "/$countryCode/$partyId/$locationId/$evseUid",
```

https://github.com/IZIVIA/ocpi-toolkit/blob/486a2f3454ab6c185a10de8cfe221f29dbf9cc23/ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/locations/LocationsCpoClient.kt#L211

should be 

```
        path = "/$countryCode/$partyId/$locationId/$evseUid/$connectorId",
```

I could create PR for it, not sure what your contribution guidelines are

**Comment by lilgallon** [comment]
Thanks for your report :)

The project has not been prioritized by the company until recently, so there is no contribution guidelines defined yet. The project will undergo many changes in the coming months and should be ready for production in summer 2024 (2.1.1 support will be dropped). Expect some refactoring in version 2.2.1, but nothing that will completely change the approach. To get back on the subject, as long as the code is correct and roughly follows established conventions, there is no reason to reject a pull request :)

I hope that time will be allocated to properly set up this repository to make it more "open-source friendly"

**Comment by lilgallon** [comment]
done in 0.0.15
