### ISSUE TITLE
Contributing command module for 2.2.1

### ISSUE THREAD

**Issue by atschabu** [IZIVIA/ocpi-toolkit#26]
While testing this library, we also implemented the command module, following the existing structure as far as possible.

We would be happy to contribute it back. I understand that this might increase your maintenance burden, so I leave it to you to decide if or when you want to receive it.

**Comment by lilgallon** [comment]
I am really happy that this lib gets used by real people other than my organization (Izivia). It's with great pleasure that we will review your PR about the command module :)

The objective of this lib is for it to be "stable" mid 2024 with real world feeback, so all OCPI modules should be implemented and tested before this milestone

**Comment by atschabu** [comment]
noted ... for now the code is rather light on tests :D ... but I have a look how you currently do the testing within this library, and create some accordingly. I'm hoping to have some time to create a PR mid December

**Comment by atschabu** [comment]
sorry for the delay ... we had to prioritize cleaning up some other modules, before we were able to provide this. Code is currently undergoing internal review, to ensure it makes sense, before we create merge request

**Comment by lilgallon** [comment]
No worries, take the time you need

**Comment by andacata** [comment]
Hi @atschabu, how's it going with the Commands implementation?

I want to start with the ChargingProfiles and it's very similar to the Commands module. So I'm interested in your approach to be aligned.

**Comment by atschabu** [comment]
I'll try pushing a draft by tomorrow

**Comment by andacata** [comment]
Thanks a lot.

**Comment by lilgallon** [comment]
Commands module is included in 0.0.25, I close this issue

Thank you again for your great work
