### ISSUE TITLE
The return type should be nullable in SessionsEmspRepository.getSession

### ISSUE THREAD

**Issue by andacata** [IZIVIA/ocpi-toolkit#28]
Hi team,
Congratulations for the good job you're doing.

As I'm testing the library, I found some issues.

https://github.com/IZIVIA/ocpi-toolkit/blob/76cfc19987e5a57d1923f5d35fc5d9f983e94d84/ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/sessions/repositories/SessionsEmspRepository.kt#L30

The return type should be nullable, because the session may not be found.

**Comment by lilgallon** [comment]
Hi, thanks for your report, you are right, it has to be fixed
