### ISSUE TITLE
Use SessionPartial as a param in SessionsEmspRepository.patchSession

### ISSUE THREAD

**Issue by andacata** [IZIVIA/ocpi-toolkit#29]
https://github.com/IZIVIA/ocpi-toolkit/blob/76cfc19987e5a57d1923f5d35fc5d9f983e94d84/ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/sessions/repositories/SessionsEmspRepository.kt#L67

In a PATCH there may be only one field, so the SessionPartial class should be used.

**Comment by lilgallon** [comment]
You are absolutely right, thanks for the report

**Comment by lilgallon** [comment]
done in 0.0.15
