### ISSUE TITLE
SessionValidation issues

### ISSUE THREAD

**Issue by atschabu** [IZIVIA/ocpi-toolkit#38]
startDate can never be greater than current time, as we would always have started in the past. Similar issue with endDate

https://github.com/IZIVIA/ocpi-toolkit/blob/28624249bac38ef148f9c7269d0b9818e7de8112/ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/sessions/services/SessionsValidators.kt#L19

And below it should be unique ID check
```
    validate(SessionPartial::evseId).isPrintableAscii().hasMaxLengthOf(36)
```
not
```
    validate(SessionPartial::evseUid).isEvseId()
```

**Comment by atschabu** [comment]
If it's not too much of a bother, would you mind cutting a release that includes this merge

**Comment by lilgallon** [comment]
sure, I'll release a new version :)

**Comment by lilgallon** [comment]
fixed in https://github.com/IZIVIA/ocpi-toolkit/releases/tag/R-0.0.16
