### ISSUE TITLE
CdrLocation uses String for coordinates

### ISSUE THREAD

**Issue by atschabu** [IZIVIA/ocpi-toolkit#40]
CdrLocation uses String instead of GeoLocation for coordinates

https://github.com/atschabu/ocpi-toolkit/blob/28624249bac38ef148f9c7269d0b9818e7de8112/ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/cdr/domain/CdrLocation.kt#L38

```
data class CdrLocation(
    val id: CiString,
    ...
    val coordinates: String,
    ...
)
```

**Comment by lilgallon** [comment]
Fixed in https://github.com/IZIVIA/ocpi-toolkit/releases/tag/R-0.0.16
