### ISSUE TITLE
Session uses Int type for kwh

### ISSUE THREAD

**Issue by atschabu** [IZIVIA/ocpi-toolkit#42]
Somewhat annoyed at myself for not noticing this while having worked on the validation issue ... but here we go .. one more single line issue + PR 😆 

Session.kwh is a number field (with decimals) but is currently using Int ... will be switching it to BigDecimal, which also brings it in sync with CDR.totalEnergy field.
<img width="676" alt="image" src="https://github.com/IZIVIA/ocpi-toolkit/assets/5340333/e2e07dd8-6181-4357-8e26-3494f06a9089">

**Comment by lilgallon** [comment]
Fixed in version 0.0.17
