### ISSUE TITLE
GET /versions with an invalid TOKEN_A returns HTTP 400 instead of an HTTP 401

### ISSUE THREAD

**Issue by andacata** [IZIVIA/ocpi-toolkit#46]
As the documentation states:

> If the header is missing or the credentials token doesn’t match any known party then the server SHALL respond with an HTTP 401 - Unauthorized status code.

But in the current implementation, the GET /versions with an incorrect CREDENTIALS_TOKEN_A is returning an HTTP 400.

**Comment by lilgallon** [comment]
Thanks for your report. A good fix should include a unit test that checks that
