### ISSUE TITLE
Duplicate domain object for BusinessDetails

### ISSUE THREAD

**Issue by atschabu** [IZIVIA/ocpi-toolkit#47]
The definition for CredentialsRole. business_details refers to definition in Location module. The following class and its dependencies can be removed from credentials module

https://github.com/IZIVIA/ocpi-toolkit/blob/5aa047f73c6d67053bfeef74aabd69dd216faabd/ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/modules/credentials/domain/BusinessDetails.kt#L8

**Comment by lilgallon** [comment]
fixed in https://github.com/IZIVIA/ocpi-toolkit/releases/tag/R-0.0.18
