### ISSUE TITLE
Automatically populate versions details Endpoints list

### ISSUE THREAD

**Issue by atschabu** [IZIVIA/ocpi-toolkit#61]
We could enhance OcpiModuleServer::registerOn(transportServer) to automatically include the newly registered module with its base path to the endpoints list.

Currently we need to manually curate list of Endoints 
```   val endpointList = listOf(
                Endpoint(
                    identifier = ModuleID.credentials,
                    role = InterfaceRole.RECEIVER,
                    url = "${config.getBaseUrl()}/${VersionNumber.V2_2_1.value}/credentials",
                ), Endpoint(
                    identifier = ModuleID.locations,
                    role = InterfaceRole.SENDER,
                    url = "${config.getBaseUrl()}/${VersionNumber.V2_2_1.value}/locations",
...
```

and provide this to a custom implementation of the VersionDetailsRepository

Instead we could provide ModuleId and role to OcpiModuleServer

```
abstract class OcpiModuleServer(
  val basePath: String,
  val module: ModuleID,
  val role: InterfaceRole,
  val versionDetailsRepo: MutableVersionDetailRepo,
) {
    protected val basePathSegments: List<PathSegment> get() = listOf(FixedPathSegment(basePath))

    protected abstract suspend fun doRegisterOn(transportServer: TransportServer)

    suspend fun registerOn(transportServer) {
      versionDetailsRepo.addEndpoint(...)
      doRegisterOn()
  }
}
```

Where MutableVersionDetailRepo holds the baseUrl already and implements VersionDetailsInterface

**Comment by lilgallon** [comment]
I agree with you, it's something that the lib should handle

**Comment by atschabu** [comment]
This ended up touching a few more parts than expected.

With this, all endpoints should have URL's based on the paths used by the servers during registration. This should simplify server setup, and avoid issues in misconfiguration.

**Comment by lilgallon** [comment]
done in 0.0.21
