### ISSUE TITLE
Provide request context to services

### ISSUE THREAD

**Issue by atschabu** [IZIVIA/ocpi-toolkit#62]
Current service interfaces are missing context information like 
* partnerUrl
* routing headers (indicating which country_code, party_id it is intended for in a multi party implementation)
* ... might be missing something else

In order to get to this information, it would be required to reimplement the server itself, which would somewhat defeat the purpose of the lib. To make the lib slightly more extensible, I can think of two ways of solving this

a) one extra layer of abstraction between server and service that has full access to the request, but most of the tedious work of deserializing body, defining paths, and variables is done. A default implementation could do validation, before handing off to service/repo interface.

b) Include a "context" object in all service interface methods (this is a very golang thing to do ... there might be a more elegant solution for kotlin) that includes the headers map, partnerUrl, and possibly more fields in the future.

**Comment by lilgallon** [comment]
We have this issue in our platform, and we will address it in the coming week (or the next one). The idea will be to use coroutines' context and put all the information inside. It will be easily extensible and will almost not impact the existing code.

We have some experience in putting information in coroutine contexts. It works well in a production environment

---

cc @xhanin - just so you have the information - we spoke about it yesterday

**Comment by atschabu** [comment]
Sounds good .. I was hoping there was a more "Kotlin way" to achieve this. This might also be useful for sake of instrumentation and monitoring.

**Comment by lilgallon** [comment]
I will start to work on it today

**Comment by lilgallon** [comment]
Just to clarify, for this issue, I will implement this part of the OCPI spec: https://github.com/ocpi/ocpi/blob/develop-2.2.1/transport_and_format.asciidoc#message-routing-headers

It requires adding:
- OCPI-to-party-id
- OCPI-to-country-code
- OCPI-from-party-id
- OCPI-from-country-code

**Comment by atschabu** [comment]
that be great ... we currently have some custom logic to extract those headers, but I'd rather see it done in the lib. Here some excerpts, hoping that might help as inspiration ;) 

```
object OcpiRoutingHeader {
    const val FROM_COUNTRY_CODE = "OCPI-from-country-code"
    const val FROM_PARTY_ID = "OCPI-from-party-id"
    const val TO_COUNTRY_CODE = "OCPI-to-country-code"
    const val TO_PARTY_ID = "OCPI-to-party-id"
}

fun HttpRequest.routingHeaders() = RoutingHeaders(
    fromCountryCode = getHeader(OcpiRoutingHeader.FROM_COUNTRY_CODE),
    fromPartyId = getHeader(OcpiRoutingHeader.FROM_PARTY_ID),
    toCountryCode = getHeader(OcpiRoutingHeader.TO_COUNTRY_CODE),
    toPartyId = getHeader(OcpiRoutingHeader.TO_PARTY_ID),
)

data class RoutingHeaders(
    val toCountryCode: String?,
    val toPartyId: String?,
    val fromCountryCode: String?,
    val fromPartyId: String?,
) {
    fun validate() {
        validate { validateLength(OcpiRoutingHeader.TO_COUNTRY_CODE, toCountryCode ?: "", 2) }
        validate { validateLength(OcpiRoutingHeader.TO_PARTY_ID, toPartyId ?: "", 3) }
        validate { validateLength(OcpiRoutingHeader.FROM_COUNTRY_CODE, fromCountryCode ?: "", 2) }
        validate { validateLength(OcpiRoutingHeader.FROM_PARTY_ID, fromPartyId ?: "", 3) }
    }

    val from
        get() = PartnerId(
            countryCode = fromCountryCode ?: "",
            partyId = fromPartyId ?: "",
        )

    val to
        get() = PartnerId(
            countryCode = toCountryCode ?: "",
            partyId = toPartyId ?: "",
        )
}

data class PartnerId(
    val countryCode: String,
    val partyId: String,
)
```

**Comment by atschabu** [comment]
beside those routing headers, will you also add the partnerUrl to the context? For several use cases (especially command response) we need to know the partner that called, so we can create a proper authenicated client for the response

**Comment by lilgallon** [comment]
I am almost done, it looks like I did the right thing because my code looks a lot like yours :)

Concerning `partnerUrl`, how should we retrieve it from the `HttpRequest`? What is your idea for that?

*Anyway, even if not done in this PR, you will be able to use a custom coroutine context to include the information you need.*

**Comment by atschabu** [comment]
it looks like all I need to do is adjust my implementation of `TransportServer`. I'll just have `secureFilter` return the partnerUrl instead of Unit, and throw that in the context. (now that I know how that works ;) )

Because currently I need a custom implementation of the server, and have to read the authorization header a second time (which is one of the reasons the #26 is coming along so slowly, as it still seemed to hacky ... using the context could solve this issue)

**Comment by lilgallon** [comment]
Oh okay I understand, I was confused on how to retrieve the `partnerUrl` as it requires using `partnerRepository`. It makes sense now
