### ISSUE TITLE
Should we open the Service classes?

### ISSUE THREAD

**Issue by andacata** [IZIVIA/ocpi-toolkit#76]
Hello.

I'm trying to implement some custom logic in the Locations service, so my first idea was to inherit from `LocationsEmspService`, call the `super` and implement my own logic. But the Service classes are closed, so it's impossible to inherit from them.

Should we open these classes to allow the inheritance or force users to implement a new class?

Maybe there is another option that I don't see. Please, feel free to comment.

Thanks.

**Comment by lilgallon** [comment]
There is no reason to not open these classes. So yes, I think we should at least open these classes
