### ISSUE TITLE
NullPointerException is thrown when pagination headers are missing

### ISSUE THREAD

**Issue by andacata** [IZIVIA/ocpi-toolkit#87]
When the required headers `X-Total-Count` or `X-Limit` are not returned from the other partner, an uncontrolled `NullPointerExeption` is thrown.

https://github.com/IZIVIA/ocpi-toolkit/blob/02302047b47442eaa430d011e38661c9bd63d59d/ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/common/HttpUtils.kt#L56-L61

**Comment by lilgallon** [comment]
It is a more general issue, see https://github.com/IZIVIA/ocpi-toolkit/issues/17

We should do that everywhere it's needed. But it is a good start
