### ISSUE TITLE
(discussion) OcpiResponseBody fields in snake_case

### ISSUE THREAD

**Issue by andacata** [IZIVIA/ocpi-toolkit#93]
I was thinking about these 2 fields in `OcpiResponseBody` that are in snake_case and I was wondering why they are not in camelCase like the rest of the variables.

https://github.com/IZIVIA/ocpi-toolkit/blob/35bbea8459543a1681a6b30e27db9c8f2cbabbea/ocpi-toolkit-2.2.1/src/main/kotlin/com/izivia/ocpi/toolkit/common/OcpiResponseBody.kt#L30-L35

**Comment by lilgallon** [comment]
There are no reason for them to be in snake_case. They will end up being serialized in snake_case like the rest. I forgot to rename them.. 😅
